jobs:
  - job: macOS
    pool:
      vmImage: 'macOS-latest'
    steps:
    - script: git submodule --quiet update --init --recursive
      displayName: 'Fetch submodules'
    - script: scripts/azure-pipelines/install-environment_macos.bash
      displayName: 'Install build environment'
    - script: scripts/azure-pipelines/build_macos.bash
      displayName: 'Build'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: macOS installer
